### ISSUE TITLE
.NET 7 support

### ISSUE THREAD

**Issue by mferraricloudsurfers** [rgvlee/EntityFrameworkCore.Testing#136]
Actually the version 4.0.2 is not compatible with .NET 7. Any programmed update?

**Comment by rgvlee** [comment]
Yes, I have made the (so far) minor changes required for .NET 7. I still have some testing to do, once that is done I will release a new branch/version.

**Comment by RobTF** [comment]
Hi, how's this going? Anything us as package users can do to help?

**Comment by rgvlee** [comment]
I've released the pre-release version [5.0.0-rc01](https://github.com/rgvlee/EntityFrameworkCore.Testing/releases/tag/v5.0.0-rc01).

This doesn't add new functionality but rather applies the minor changes to get the existing solution working for EFCore 7.

Let me know if you run into any issues; the extensive set of tests are all green so I don't anticipate any. I'll release 5.0.0 over the weekend if I don't hear otherwise.

**Comment by RobTF** [comment]
Looks good so far!

**Comment by rgvlee** [comment]
5.0.0 has been released. Please raise any bugs as new issues. Thanks Lee
