### ISSUE TITLE
Add .NET 9 support

### ISSUE THREAD

**Issue by rgvlee** [rgvlee/EntityFrameworkCore.Testing#156]
As per the title

**Comment by rgvlee** [comment]
9.0.0-rc01 published

**Comment by rgvlee** [comment]
@MrDWilson I don't have any .NET projects at the moment, want to take the pre-release for a spin and let me know how you go?

**Comment by MrDWilson** [comment]
Gave 9.0.0-rc02 a try on my project and all looked to be functioning well for me, no issues.

**Comment by rgvlee** [comment]
9.0.0 published, thanks for your help!

**Comment by durandt** [comment]
Hi @rgvlee, thank you for adding .NET 9 support!

Would you consider supporting .NET 8 for the 9.x.x packages?

Here me out: I don't know if Microsoft has documented their versioning strategy for their libraries published as NuGet packages, but most libraries now follow the .NET version number, for example Microsoft.Extensions.Logging v9.0.0

From what I have observed, most Microsft.* 9.x.x packages do still support .NET 8 (I guess because it is the LTS version). .NET 8 has an EOL 6 months later than .NET 9 and I think many devs will stick to LTS:es to minimise the overhead created by updating to the new dotnet runtime every year.

Adding support for .NET 8 to EntityFrameworkCore.Testing would allow devs targeting .NET 8 (or the current LTS) to update all Microsoft dependencies to v9.0.0 (which will be required to avoid future vulnerabilities) without getting errors or warnings from NuGet (Since EntityFrameworkCore.Testing.NSubstitute requires for example Microsoft.Extensions.Logging (>= 8.0.0 && < 9.0.0), which clashes with having a direct reference to Microsoft.Extensions.Logging 9.0.0 in my project)

**Comment by durandt** [comment]
(I can of course create a separate issue or/and a PR if you wish so)

**Comment by rgvlee** [comment]
Make sense, I didn't notice they had done that (I don't have any current projects using EFCore in .NET 8 or 9 since switching to a new role earlier this year :/).

EntityFrameworkCore.Testing.NSubstitute 9.0.0 shouldn't require Microsoft.Extensions.Logging >= 8.0.0 && < 9.0.0

![image](https://github.com/user-attachments/assets/d71446f0-29ba-40b7-876a-d370c321f17b)

**Comment by durandt** [comment]
Thank you for your quick reply!

I should have been more specific, I meant _EntityFrameworkCore.Testing.NSubstitute **8.x.x** requires for example Microsoft.Extensions.Logging (>= 8.0.0 && < 9.0.0)_
(And EntityFrameworkCore.Testing.NSubstitute requires .NET 9 so the issue is that you cannot target .net8 AND use Microsoft.Extensions.Logging 9.0.0 without nuget version conflict warnings when installing EntityFrameworkCore.Testing.NSubstitute **8.x.x**)

If you want I can create a repro to make it clearer :D

**Comment by rgvlee** [comment]
Yeah that makes more sense
I can see some MS.* libraries target both .net 8 and .net 9, but looks like efcore targets just .net 8. Probably easier to change the target framework to 8 for this library, than multi target.
Taking a look now

**Comment by rgvlee** [comment]
9.0.1-rc01 published, give it a whirl. If that looks good I'll release 9.0.1.

**Comment by durandt** [comment]
> Restored [...]\Dotnet8SampleApis.Business.Test.csproj (in 1,47 sec).
> Successfully installed 'EntityFrameworkCore.Testing.NSubstitute 9.0.1-rc01' to Dotnet8SampleApis.Business.Test
> Successfully installed 'Microsoft.EntityFrameworkCore.InMemory 9.0.0' to Dotnet8SampleApis.Business.Test
> Successfully installed 'rgvlee.Core 1.2.1' to Dotnet8SampleApis.Business.Test
> Executing nuget actions took 163 ms
> [Notification][Install] EntityFrameworkCore.Testing.NSubstitute v9.0.1-rc01 was successfully installed to Dotnet8SampleApis.Business.Test

Looks good to me. Working properly. Thank you @rgvlee

**Comment by rgvlee** [comment]
9.0.1 published just now
