### ISSUE TITLE
.net 5 support

### ISSUE THREAD

**Issue by petrce** [rgvlee/EntityFrameworkCore.Testing#42]
hi, can I help anyhow with the .net 5 support?
Our project became very dependent on your great library, so rather than rewrite all the tests to remove the dependency on your library, I would rather help to update it to net 5 :)

**Comment by rgvlee** [comment]
Hey buddy, I'm most of the way through it... just haven't had the time to finish it off.

I've pushed feature/AddDotNet5Support which was the working Moq version as at just over a month ago. I've since done the nsub version and I've just got a few unit tests to sort out and I should be able to release an RC. I'll try to make some time for it as I've got a new .NET Core 2 and .NET Core 3 version to release as well.

**Comment by petrce** [comment]
awesome, thank you very much, we are happy to test the RC package of nsub ;)

**Comment by rgvlee** [comment]
I've resolved the failing tests to just the Moq version. Some sort of weird enumerator behaviour that exists in the existing versions as well. The changes are moving in code review. Shouldn't be too much longer.

**Comment by rgvlee** [comment]
I've published version 3.0.0 which provides support for .NET 5 for both moq and nsub.

Sorry for the timeliness. It was quite a big change, part of the overhead is that I like to keep the code base for the .NET Core 2/.NET Core 3/.NET 5 branches as close as possible so some changes were somewhat replicated.

I'll close this request soon; if you encounter any issues let me know in a new issue. I've got pretty good coverage so I'm not anticipating any show stoppers.
